version: "3.9"

services:

  rag-pdf-chatbot:

    build: .

    container_name: rag_pdf_chatbot

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    env_file:
      - .env

    restart: unless-stopped